#the freeipa container
gitweb:
    hostname: gitweb.example.test
    build: .
    ports:
        - "8080:80"
        - "8443:443"
    volumes:
        - /tmp/var/lib/git:/var/lib/git:rw
    environment:
        - http_proxy
        - https_proxy
        - ftp_proxy
        - no_proxy
        - GIT_PROJECT_NAME=dummy
